### ISSUE TITLE
AWS:EC2 Roadmap

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#273]
## Here is a short roadmap of things we want in aws:ec2
@jonathangold is hacking on all this stuff. We build this roadmap together.

### Short term
- [ ] Finish off sns stuff https://github.com/purpleidea/mgmt/pull/272
- [ ] LongPollWatch bug: `WaitUntilInstanceStopped` doesn't detect when instances terminate

### Medium term (cool/important stuff!)
- [ ] Mgmt Bootstrapping param which takes over `UserData` parameter.
- [ ] Send->Recv to "send" the AWS instance IP address on startup to some downstream resource. https://ttboj.wordpress.com/2016/12/07/sendrecv-in-mgmt/ (are there any other values we should produce?)
- [ ] Can we "send" (send/recv style) an auth (ssh?) key that gets "generated" after bootup? Maybe we should be "recv"-ing a public key and pushing it into this resource or as a parameter?

### Low priority / long term
- [ ] `SQS` Watching (what are the benefits?)
- [ ] Refactor aws utility functions into some internal lib for use with possible future aws resources (s3?)

Feel free to suggest ideas / improvements on all of this :)

**Comment by jonathangold** [comment]
We should add: Research mock clients and write tests.
Testing methods that don't require an aws, cwe or sns client could be included or added as an additional task.

**Comment by jonathangold** [comment]
Just some thoughts on SQS Watch benefits:
- No state-checking (longpollWatch does different things depending on instance/definition state)
- Compatible with existing CloudWatch code
- Very similar to existing SNS code (ie. snsAuthorize -> sqsAuthorize is only a few lines. It is even likely possible to use one method for both.)
- Can be generalized and applied to future aws resources, unlike longpollWatch

I'll edit this comment if I think of anything else.

**Comment by jonathangold** [comment]
@purpleidea See #284 re: SNS stuff.

**Comment by jonathangold** [comment]
Here's a list of functions a mock ec2 client interface needs for testing (this does not include sns):
- DescribeInstances
- StartInstances
- StopInstances
- TerminateInstances
- RunInstances
- CreateTags
- WaituntilInstanceExistsWithContext
- WaituntilInstanceStartedWithContext
- WaituntilInstanceStoppedWithContext
